default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5

development:
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DEFAULT_HOST'] %>

test:
  <<: *default

production:
  <<: *default
